[package]
name = "rs8583"
version = "0.2.0"
authors = ["Alex Unigovsky <unik@devrandom.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.17"
bytes = "0.5"
encoding8 = "0.3"
thiserror = "1.0"
