[package]
name = "rs8583"
version = "0.1.0"
authors = ["Alex Unigovsky <unik@devrandom.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmaps = "2.0.0"
bytes = "0.5.4"
failure = "0.1.8"
typenum = "1.11.2"
